spring.application.name=crypto-divergence

# Binance base WebSocket URL (for maintainability)
binance.ws.base-url=wss://stream.binance.com:9443/stream?streams=

# Optimize below by using symbols to construct the full URL dynamically in the code, instead of hardcoding it here like below
# binance.ws.url=wss://stream.binance.com:9443/stream?streams=btcusdt@ticker/ethusdt@ticker/solusdt@ticker
# Binance symbols to subscribe (comma-separated, easy to maintain)
binance.ws.symbols=btcusdt,ethusdt,solusdt,bnbusdt,xrpusdt,adausdt,dogeusdt,maticusdt,dotusdt,linkusdt

# Reconnect delay in ms
binance.ws.reconnect-delay-ms=3000